### PR TITLE
StackOverflowError fixed.

### LINKED ISSUE #356: StackOverflowError with generic types
There's a circle in `TypeName.get/list`, `ParameterizedTypeName.get` and `TypeVariableName.get`. The following test:
```java
  private <E extends Enum<E>> E recursiveEnum(E[] values) {
    return values[0];
  }
  
  @Test public void genericTypes() throws Exception {
    Method recursiveEnum = getClass().getDeclaredMethod("recursiveEnum", Enum[].class);
    TypeName.get(recursiveEnum.getReturnType());
    TypeName.get(recursiveEnum.getGenericReturnType()); // StackOverflowError !!!
    TypeName.get(recursiveEnum.getParameterTypes()[0]);
    TypeName.get(recursiveEnum.getGenericParameterTypes()[0]); // StackOverflowError !!!
  }
```
produces a endless stack trace like:
```
Caused by: java.lang.StackOverflowError
	at java.lang.Class.getSimpleBinaryName(Class.java:1443)
	at java.lang.Class.getSimpleName(Class.java:1309)
	at com.squareup.javapoet.ClassName.get(ClassName.java:113)
	at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:76)
	at com.squareup.javapoet.TypeName.get(TypeName.java:260)
	at com.squareup.javapoet.TypeName.list(TypeName.java:280)
	at com.squareup.javapoet.TypeVariableName.get(TypeVariableName.java:129)
	at com.squareup.javapoet.TypeName.get(TypeName.java:266)
	at com.squareup.javapoet.TypeName.list(TypeName.java:280)
	at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:77)
	at com.squareup.javapoet.TypeName.get(TypeName.java:260)
	at com.squareup.javapoet.TypeName.list(TypeName.java:280)
	at com.squareup.javapoet.TypeVariableName.get(TypeVariableName.java:129)
	at com.squareup.javapoet.TypeName.get(TypeName.java:266)
	at com.squareup.javapoet.TypeName.list(TypeName.java:280)
	at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:77)
	at com.squareup.javapoet.TypeName.get(TypeName.java:260)
```

### PR DESCRIPTION
**Pull request by sormuras**
Fixes #356 analog to the `TypeName.get(TypeMirror)` fix by Eamonn.
See https://github.com/square/javapoet/commit/6551850b3eaa4f5ff4b6ce6a2b2102d281a11fee

### CODE REVIEW

File: src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+ * limitations under the License.
+ */
+package com.squareup.javapoet;
+
+import static org.junit.Assert.assertEquals;
+
+import java.util.List;
+import org.junit.Test;
+
+public class AnnotatedTypeNameTest {
```
Comment (swankjesse) [inline src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java]: Probably needs to come out of this PR, now that I’ve murdered AnnotatedTypeName

File: src/test/java/com/squareup/javapoet/TypeNameTest.java [hunk 2]
```diff
@@ -32,6 +33,18 @@
 
 public class TypeNameTest {
 
+  protected <E extends Enum<E>> E generic(E[] values) {
+    return values[0];
+  }
+
+  @Test public void genericType() throws Exception {
```
Comment (swankjesse) [inline src/test/java/com/squareup/javapoet/TypeNameTest.java]: Awesome.

**Comment by swankjesse** [comment]
LGTM! The `AnnotatedTypeName` change needs to come out though, unfortunately.

**Comment by sormuras** [comment]
Out it is.
